repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v4.0.0-alpha.8"
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@2.1.0
          - prettier-plugin-go-template@0.0.13

exclude: ^(web/src/css/semantic\.css|web/src/js/semantic\.min\.js)
