name: k8s-deploy

on:
  push:
    branches:
      - main
      - k8s-deploy

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  production-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out latest commit
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: osuAkatsuki/hanayo

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/hanayo:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/hanayo:${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Get kubeconfig from github secrets
        run: |
            mkdir -p $HOME/.kube
            echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config
            sudo chown $(id -u):$(id -g) $HOME/.kube/config
      - name: Install helm
        uses: azure/setup-helm@v3
        with:
          version: "latest"
          token: ${{ secrets.GITHUB_TOKEN }}
        id: install

      - name: Install helm-diff
        run: helm plugin install https://github.com/databus23/helm-diff

      - name: Checkout common-helm-charts repo
        uses: actions/checkout@v3
        with:
          repository: osuAkatsuki/common-helm-charts
          token: ${{ secrets.COMMON_HELM_CHARTS_PAT }}
          path: common-helm-charts

      - name: Show manifest diff since previous release
        run: |
          helm diff upgrade \
          --allow-unreleased \
          --values chart/values.yaml \
          hanayo-production \
          common-helm-charts/microservice-base/
      - name: Deploy service to production cluster
        run: |
          helm upgrade \
            --install \
            --atomic \
            --wait --timeout 480s \
            --values chart/values.yaml \
            hanayo-production \
            common-helm-charts/microservice-base/
